package:
  name: vlachos-group-additivity
  version: "1.0.0"

source:
  git_rev: "development"
  git_url: "https://github.com/jtfrey/VlachosGroupAdditivity.git"

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - rdkit
    - scipy
    - numpy
    - IPython
    - PyYAML

about:
  home: "https://github.com/VlachosGroup/VlachosGroupAdditivity"
  license: MIT
  license_file: LICENSE.md
